---
- name: Configure Postgres guest
  hosts: postgres
  roles:
    - ssh_keys
    - postgres

- name: Configure dev guest
  hosts: dev
  roles:
    - ssh_keys
    - tailscale
    - docker
    - devbox

- name: Configure paperless guest
  hosts: paperless
  roles:
    - ssh_keys
    - docker
    - paperless
