#!/usr/bin/env bash
# Regenerate the Ansible guest inventory from Terraform outputs.
# The static host inventory (00-static.yml) is untouched; Ansible merges both.
set -euo pipefail

cd "$(dirname "$0")/.."
OUT="ansible/inventory/10-guests.ini"

# Reading remote state needs the backend creds + encryption passphrase.
[ -f terraform/.env.sh ] && { set -a; . terraform/.env.sh; set +a; }

{
  echo "# GENERATED by scripts/tf-to-inventory.sh — do not edit by hand."
  tofu -chdir=terraform output -json guests | jq -r "
    to_entries
    | group_by(.value.group)
    | map(
        \"[\" + .[0].value.group + \"]\",
        (.[] | .key + \" ansible_host=\" + .value.ip + \" ansible_user=root\")
      )
    | flatten
    | .[]
  "
} > "$OUT"

echo "Wrote $OUT"
