#!/usr/bin/env bash
# Regenerate the Ansible guest inventory from Terraform outputs.

set -euo pipefail

cd "$(dirname "$0")/.."
OUT="ansible/inventory/10-guests.ini"

[ -f terraform/.env.sh ] && { set -a; . terraform/.env.sh; set +a; }


{
  cd terraform
  echo "# GENERATED by scripts/tf-to-inventory.sh — do not edit by hand."
  tofu output -json guests | jq -r "
    to_entries
    | group_by(.value.group)
    | map(
        \"[\" + .[0].value.group + \"]\",
        (.[] | .key + \" ansible_host=\" + .value.ip + \" ansible_user=root\")
      )
    | flatten
    | .[]
  "
} > "$OUT"

echo "Wrote $OUT"
