---
- name: Add Docker apt repo
  ansible.builtin.deb822_repository:
    name: docker
    types: deb
    uris: https://download.docker.com/linux/debian
    suites: "{{ ansible_facts['distribution_release'] }}"
    components: stable
    signed_by: https://download.docker.com/linux/debian/gpg
    state: present

- name: Install Docker engine and compose plugin
  ansible.builtin.apt:
    name: "{{ docker_packages }}"
    state: present
    update_cache: true

- name: Ensure docker is running
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add users to the docker group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: true
  loop: "{{ docker_users }}"
